// db/seed/xtreinos-dados.ts
// ⚠️  SÓ EDITE ESTE ARQUIVO quando tiver um novo xtreino!
// Nada de lógica aqui, só arrays com os dados brutos.

export interface XtreinoRaw {
  id: number;
  date: string;
  colocacoes: [teamName: string, q1: number, q2: number, q3: number][];
  jogadores: [teamName: string, playerName: string, q1: number, q2: number, q3: number][];
}

export const xtreinosRaw: XtreinoRaw[] = [
  // ========================================
  // XTreino 1 — 2026-04-30
  // ========================================
  {
    id: 1,
    date: "2026-04-30",
    colocacoes: [
      ["UGD Threat", 1, 1, 3],
      ["FURY", 2, 6, 6],
      ["RED", 3, 6, 6],
      ["UGD Royal", 4, 5, 6],
      ["Λつつ", 5, 2, 2],
      ["ODS", 6, 6, 6],
      ["INF", 6, 4, 6],
      ["CMF", 6, 3, 4],
      ["Eternity", 6, 6, 1],
      ["LMF", 6, 6, 5],
    ],
    jogadores: [
      ["UGD Threat", "UGD Ares", 7, 0, 0],
      ["UGD Threat", "UGD Kaze", 6, 2, 6],
      ["UGD Threat", "UGD Treon", 5, 12, 8],
      ["UGD Threat", "UGD ARISE", 6, 0, 0],
      ["UGD Threat", "UGD Neo", 0, 5, 8],
      ["UGD Threat", "Rivers AR", 0, 5, 9],
      ["FURY", "VN' FURY", 4, 0, 0],
      ["FURY", "Creedz FURY", 4, 0, 0],
      ["FURY", "perfection z", 3, 0, 0],
      ["FURY", "Diana FURY", 5, 0, 0],
      ["RED", "REÐ LANGØ", 9, 0, 0],
      ["RED", "REÐ Zadock", 2, 0, 0],
      ["RED", "REÐ M4RTINA", 8, 0, 0],
      ["RED", "REÐ APENAS", 3, 0, 0],
      ["UGD Royal", "UGD Z", 9, 0, 0],
      ["UGD Royal", "Dexz", 3, 0, 0],
      ["UGD Royal", "UGD Weenot", 8, 0, 0],
      ["UGD Royal", "OFFz", 0, 16, 0],
      ["UGD Royal", "MayaZ", 0, 8, 0],
      ["UGD Royal", "WenoTz", 0, 5, 0],
      ["UGD Light", "DEATH", 3, 3, 0],
      ["UGD Light", "UGD Psycho", 0, 0, 0],
      ["UGD Light", "I miss her", 0, 0, 0],
      ["UGD Light", "UGD Kyz", 0, 0, 0],
      ["Λつつ", "Λつつ_$CAVEIRA", 3, 0, 0],
      ["Λつつ", "Λつつ Aninha", 4, 0, 0],
      ["Λつつ", "ØNE ???", 1, 0, 0],
      ["Λつつ", "Λつつ Unknown", 1, 0, 0],
      ["Λつつ", "Striker71", 0, 2, 2],
      ["Λつつ", "『PsS-KINN-ボ", 0, 2, 1],
      ["Λつつ", "Striker81", 0, 3, 4],
      ["Λつつ", "ΛΞT Jentexz", 0, 8, 9],
      ["ODS", "[ODS].STROG", 3, 0, 0],
      ["ODS", "[ODS] vantex", 0, 0, 0],
      ["ODS", "Az Aamon", 0, 0, 0],
      ["INF", "「INF」Noxz7'", 0, 3, 0],
      ["INF", "「INF」RINNEGA", 0, 4, 0],
      ["INF", "「INF」BLAZE", 0, 2, 0],
      ["INF", "「INF」GOAT", 0, 6, 0],
      ["CMF", "CMF Lyx7", 0, 3, 8],
      ["CMF", "CMF Leo", 0, 2, 8],
      ["CMF", "CMF Stygian", 0, 3, 4],
      ["CMF", "CMF Syx", 0, 5, 8],
      ["Eternity", "Muggle 永", 0, 0, 3],
      ["Eternity", "DamønTTK 永", 0, 0, 8],
      ["Eternity", "Black 永", 0, 0, 7],
      ["Eternity", "Givas'xX 永", 0, 0, 4],
      ["LMF", "LMF_mtfacil", 0, 0, 2],
      ["LMF", "LMF_XIT", 0, 0, 2],
      ["LMF", "LMF_Boss", 0, 0, 2],
      ["LMF", "LMF_RICHIMO", 0, 0, 4],
    ],
  },
  // ========================================
  // XTreino 2 — 2026-05-07
  // ========================================
  {
    id: 2,
    date: "2026-05-07",
    colocacoes: [
      ["UGD Threat", 1, 1, 1],
      ["CMF", 2, 4, 5],
      ["INF", 3, 6, 4],
      ["LMF", 4, 2, 6],
      ["Misturado", 5, 6, 3],
      ["Eternity", 6, 3, 6],
      ["RED", 6, 5, 2],
    ],
    jogadores: [
      ["UGD Threat", "UGD Ares", 9, 16, 14],
      ["UGD Threat", "UGD Kaze", 11, 15, 8],
      ["UGD Threat", "UGD ARISE", 5, 10, 8],
      ["UGD Threat", "UGD Treon", 9, 12, 12],
      ["CMF", "CMF Stygian", 7, 2, 6],
      ["CMF", "CMF Lyx7", 12, 4, 7],
      ["CMF", "CMF Leo", 9, 6, 4],
      ["CMF", "CMF Syx", 7, 4, 6],
      ["INF", "INF Noxz7", 6, 0, 3],
      ["INF", "INF GOAT", 5, 0, 3],
      ["INF", "INF BARONI", 5, 0, 5],
      ["INF", "INF RINNEGA", 4, 0, 1],
      ["LMF", "LMF_LACERDA", 4, 0, 0],
      ["LMF", "LMF_RICHIMO", 3, 1, 0],
      ["LMF", "LMF_mtfacil", 9, 2, 0],
      ["LMF", "LMF_XIT", 4, 3, 0],
      ["LMF", "LMF_Boss", 0, 0, 0],
      ["Misturado", "REVERSE_", 0, 0, 6],
      ["Misturado", "INF RONY", 3, 0, 4],
      ["Misturado", "INF BADBOY", 2, 0, 0],
      ["Misturado", "TOP FreeKill", 0, 0, 3],
      ["Eternity", "Nofear", 0, 2, 0],
      ["Eternity", "Damøn.TTK", 0, 5, 0],
      ["Eternity", "Muggle", 0, 4, 0],
      ["Eternity", "Kennedy", 0, 6, 0],
      ["RED", "RED APENAS", 0, 5, 1],
      ["RED", "ASTRO", 0, 6, 4],
      ["RED", "REÐ snow777", 0, 2, 5],
      ["RED", "REÐ Sunraku", 0, 3, 0],
    ],
  },
  // ========================================
  // XTreino 3 — 2026-05-19
  // ========================================
  {
    id: 3,
    date: "2026-05-19",
    colocacoes: [
      ["UGD Threat", 1, 4, 1],
      ["RED", 2, 7, 4],
      ["RED Magic BR", 3, 1, 7],
      ["LMF", 4, 6, 5],
      ["KOV", 5, 5, 3],
      ["CMF", 7, 3, 2],
      ["Eternity", 6, 2, 6],
    ],
    jogadores: [
      ["UGD Threat", "UGD Treon", 11, 12, 13],
      ["UGD Threat", "UGD cool7", 8, 10, 6],
      ["UGD Threat", "UGD Kaze", 13, 1, 8],
      ["UGD Threat", "UGD ARISE", 8, 8, 4],
      ["RED", "RED snow777", 3, 0, 1],
      ["RED", "RED APENAS", 7, 0, 4],
      ["RED", "CF ALMEIDA", 0, 0, 1],
      ["RED", "LMF Boss", 5, 0, 3],
      ["RED Magic BR", "RED LANGO", 4, 7, 0],
      ["RED Magic BR", "RED KENNZY", 6, 6, 0],
      ["RED Magic BR", "MOL ADRIAN", 2, 1, 0],
      ["RED Magic BR", "LXELTINHO", 1, 5, 0],
      ["LMF", "LMF LACERDA", 2, 0, 3],
      ["LMF", "LMF CALOP12", 1, 0, 1],
      ["LMF", "LMF mtfacil", 1, 0, 5],
      ["LMF", "LMF XIT", 1, 0, 0],
      ["KOV", "KOV FushyX", 5, 2, 2],
      ["KOV", "KOV ADAN", 7, 5, 2],
      ["KOV", "TTKKAIKE", 5, 2, 0],
      ["KOV", "KOV ALONE", 0, 1, 5],
      ["CMF", "CMF Syx", 0, 7, 7],
      ["CMF", "CMF Lyx7", 0, 7, 3],
      ["CMF", "CMF MOIZO", 0, 4, 5],
      ["CMF", "CMF Stygian", 0, 3, 7],
      ["Eternity", "RED REZE", 0, 0, 0],
      ["Eternity", "Muggle", 0, 6, 0],
      ["Eternity", "Shxrk", 0, 4, 0],
    ],
  },
  // ========================================
  // XTreino 4 — 2026-05-21
  // ========================================
  {
    id: 4,
    date: "2026-05-21",
    colocacoes: [
      ["UGD Threat", 1, 3, 4],
      ["Time I", 2, 6, 3],
      ["CMF", 3, 4, 1],
      ["RED", 4, 2, 2],
      ["KOV", 5, 1, 6],
      ["Time E", 6, 5, 5],
    ],
    jogadores: [
      ["UGD Threat", "UGD Kaze", 5, 4, 6],
      ["UGD Threat", "UGD cool7", 7, 7, 6],
      ["UGD Threat", "UGD Treon", 14, 4, 3],
      ["UGD Threat", "UGD ARISE", 9, 9, 1],
      ["Time I", "hcky", 4, 0, 0],
      ["Time I", "ASTRO", 8, 0, 8],
      ["Time I", "GzmAkaza", 2, 0, 9],
      ["Time I", "AimColor", 2, 0, 0],
      ["Time I", "iDiaasz", 0, 0, 2],
      ["Time I", "Jtpe", 0, 0, 0],
      ["CMF", "CMF Leo", 8, 7, 11],
      ["CMF", "CMF Stygian", 5, 6, 5],
      ["CMF", "CMF Syx", 14, 10, 9],
      ["CMF", "CMF MOIZO", 2, 3, 7],
      ["RED", "RED APENAS", 7, 8, 7],
      ["RED", "RED- REZE", 1, 5, 0],
      ["RED", "RED-MOREIRA", 0, 2, 3],
      ["RED", "RED-Alemão", 2, 3, 2],
      ["KOV", "KOV FushyX", 1, 5, 0],
      ["KOV", "KOV ADAN", 0, 7, 0],
      ["KOV", "YoSurper", 7, 3, 0],
      ["KOV", "AET Jentexz", 1, 11, 0],
      ["Time E", "PAIN SWAN", 0, 0, 1],
      ["Time E", "Poindexter", 0, 0, 2],
      ["Time E", "ONE-Javi", 0, 0, 0],
      ["Time E", "morqesb", 0, 0, 1],
    ],
  },
  // ========================================
  // XTreino 5 — 2026-06-08
  // ========================================
  {
    id: 5,
    date: "2026-06-08",
    colocacoes: [
      ["CMF ATLANTIC", 1, 2, 1],
      ["EmE", 2, 4, 3],
      ["FURY ELITE", 3, 1, 4],
      ["UGD OLYMPIQUE", 4, 10, 12],
      ["REÐ Outlaws", 5, 9, 7],
      ["UGD Threat", 6, 11, 5],
      ["UGD LIGHT", 7, 3, 11],
      ["♱VØID×STRIKE♱", 8, 13, 6],
      ["7KW_LHETAL", 9, 7, 8],
      ["FURY ROYAL", 10, 8, 2],
      ["UGD LEGENDS", 11, 6, 9],
      ["K4F", 12, 5, 10],
      ["CMF ASSALT", 13, 12, 13],
    ],
    jogadores: [
      ["UGD OLYMPIQUE", "Weenot", 4, 4, 0],
      ["UGD OLYMPIQUE", "Duardin", 1, 0, 2],
      ["UGD OLYMPIQUE", "Striker", 3, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 4, 1, 1],
      ["UGD LEGENDS", "Santz", 3, 11, 10],
      ["UGD LEGENDS", "hell", 4, 3, 6],
      ["UGD LEGENDS", "Ohara", 2, 0, 0],
      ["UGD LEGENDS", "Rafa", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 0, 9, 4],
      ["UGD LEGENDS", "Buzeira", 1, 1, 2],
      ["UGD LIGHT", "Kyz", 5, 1, 2],
      ["UGD LIGHT", "Zann", 6, 1, 3],
      ["UGD LIGHT", "Psycho", 5, 1, 0],
      ["UGD LIGHT", "Chino", 5, 3, 5],
      ["FURY ROYAL", "VN", 9, 6, 11],
      ["FURY ROYAL", "NOKI", 4, 4, 4],
      ["FURY ROYAL", "EGOIST", 4, 6, 6],
      ["FURY ROYAL", "MARTNA", 9, 5, 2],
      ["FURY ELITE", "DIANA", 2, 1, 3],
      ["FURY ELITE", "hluydex", 2, 3, 2],
      ["FURY ELITE", "TRY", 4, 7, 4],
      ["FURY ELITE", "DEXZ", 5, 4, 3],
      ["CMF ATLANTIC", "CMF Léo", 18, 19, 17],
      ["CMF ATLANTIC", "CMF Syx", 10, 12, 23],
      ["CMF ATLANTIC", "CMF Kira", 8, 6, 11],
      ["CMF ATLANTIC", "CMF Moizo", 13, 6, 7],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 1, 0],
      ["CMF ASSALT", "CMF Max", 0, 3, 0],
      ["CMF ASSALT", "CMF Thxxxz", 3, 1, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.D_R", 0, 0, 1],
      ["♱VØID×STRIKE♱", "♱Vøid♱+gute", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.nino", 2, 0, 1],
      ["♱VØID×STRIKE♱", "™VØID°⁷⁷⁷", 1, 0, 0],
      ["REÐ Outlaws", "REÐ MoraesBC", 4, 3, 2],
      ["REÐ Outlaws", "REÐ Felpz", 4, 3, 5],
      ["REÐ Outlaws", "REÐ Skibidi", 3, 3, 0],
      ["REÐ Outlaws", "REÐ Apenas", 8, 0, 6],
      ["K4F", "k4F urso", 2, 1, 2],
      ["K4F", "K4F nine", 4, 1, 0],
      ["K4F", "K4F gui", 3, 9, 4],
      ["K4F", "Alek", 2, 0, 1],
      ["7KW_LHETAL", "(NTC)patrikm", 6, 8, 0],
      ["7KW_LHETAL", "_061_kakashi", 4, 17, 8],
      ["7KW_LHETAL", "RL.MATADOR☠️", 10, 11, 5],
      ["7KW_LHETAL", "Fefe_🎭🇧🇷", 4, 12, 7],
      ["EmE", "Yeezy", 2, 7, 4],
      ["EmE", "geldeysito", 9, 9, 17],
      ["EmE", "EME々Akaza", 4, 5, 10],
      ["EmE", "EME々Lulu", 3, 10, 8],
      ["UGD Threat", "Cool", 4, 6, 6],
      ["UGD Threat", "Treon", 6, 4, 8],
      ["UGD Threat", "Kaze", 1, 1, 4],
      ["UGD Threat", "LMF_BOSS", 2, 1, 1],
    ],
  },
  // ========================================
  // XTreino 6 — 2026-06-09
  // ========================================
  {
    id: 6,
    date: "2026-06-09",
    colocacoes: [
      ["FURY ELITE", 1, 2, 5],
      ["EmE", 2, 3, 12],
      ["CMF ATLANTIC", 3, 6, 6],
      ["UGD OLYMPIQUE", 4, 7, 4],
      ["UGD LIGHT", 5, 5, 9],
      ["♱VØID×STRIKE♱", 6, 10, 11],
      ["FURY ROYAL", 7, 1, 3],
      ["REÐ Outlaws", 8, 9, 2],
      ["K4F", 9, 8, 10],
      ["UGD Threat", 10, 4, 1],
      ["CMF ASSALT", 11, 11, 7],
      ["TROPA DO XXX", 12, 12, 8],
    ],
    jogadores: [
      ["FURY ROYAL", "VN", 3, 11, 8],
      ["FURY ROYAL", "EGOIST", 4, 20, 4],
      ["FURY ROYAL", "MARTNA", 6, 10, 12],
      ["FURY ROYAL", "OFF", 3, 10, 7],
      ["EmE", "Yeezy", 6, 4, 0],
      ["EmE", "EME々Akaza", 6, 0, 0],
      ["EmE", "MK4", 6, 8, 0],
      ["EmE", "EME々Lulu", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 5, 6, 4],
      ["UGD OLYMPIQUE", "Duardin", 5, 0, 1],
      ["UGD OLYMPIQUE", "Lorex", 4, 0, 3],
      ["UGD OLYMPIQUE", "Cants", 8, 1, 4],
      ["UGD OLYMPIQUE", "Striker", 0, 0, 0],
      ["UGD OLYMPIQUE", "Sant", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Léo", 6, 9, 4],
      ["CMF ATLANTIC", "CMF Syx", 7, 5, 8],
      ["CMF ATLANTIC", "CMF Kira", 5, 0, 0],
      ["CMF ATLANTIC", "CMF Moizo", 5, 4, 2],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 3],
      ["CMF ASSALT", "CMF Lynx7", 2, 2, 4],
      ["CMF ASSALT", "CMF Max", 3, 0, 3],
      ["CMF ASSALT", "CMF Thxxxz", 2, 2, 5],
      ["♱VØID×STRIKE♱", "♱Vøid♱.D_R", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱+gute", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.nino", 0, 0, 0],
      ["♱VØID×STRIKE♱", "™VØID°⁷⁷⁷", 0, 0, 0],
      ["♱VØID×STRIKE♱", "√Vøid√T9", 0, 0, 0],
      ["FURY ELITE", "DIANA", 4, 2, 2],
      ["FURY ELITE", "RAUAN", 11, 2, 1],
      ["FURY ELITE", "HLUYDEX", 5, 3, 1],
      ["FURY ELITE", "DEX", 5, 4, 1],
      ["FURY ELITE", "KAY", 0, 0, 0],
      ["FURY ELITE", "TRY", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 1, 1, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 2],
      ["TROPA DO XXX", "XXX 🪠🪠🪠", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 6, 2],
      ["K4F", "K4F  Éourso", 2, 0, 0],
      ["K4F", "K4F  Gui", 0, 0, 0],
      ["K4F", "K4F  Zaza", 2, 6, 0],
      ["K4F", "K4F  Nine", 0, 5, 0],
      ["K4F", "wend", 0, 0, 0],
      ["K4F", "aleke", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 4, 0, 2],
      ["UGD LIGHT", "Zann", 4, 1, 3],
      ["UGD LIGHT", "Psycho", 8, 3, 1],
      ["UGD LIGHT", "Chino", 8, 0, 3],
      ["UGD LIGHT", "Sant", 0, 0, 0],
      ["REÐ Outlaws", "REÐ  MoraesBC", 2, 0, 0],
      ["REÐ Outlaws", "REÐ  Felpz", 0, 1, 1],
      ["REÐ Outlaws", "REÐ  Skibidi", 4, 0, 3],
      ["REÐ Outlaws", "REÐ  Apenas", 2, 2, 6],
      ["UGD Threat", "Cool", 1, 10, 4],
      ["UGD Threat", "Treon", 3, 8, 5],
      ["UGD Threat", "Kaze", 1, 6, 3],
      ["UGD Threat", "Arise", 0, 0, 0],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["UGD Threat", "Santz", 2, 4, 5],
    ],
  },
  // ========================================
  // XTreino 7 — 2026-06-10
  // ========================================
  {
    id: 7,
    date: "2026-06-10",
    colocacoes: [
      ["CMF ATLANTIC", 1, 7, 3],
      ["UGD Threat + Olympique", 6, 5, 4],
      ["FURY ROYAL", 3, 3, 1],
      ["EmE", 4, 2, 10],
      ["UGD Legends", 2, 1, 6],
      ["CMF ASSALT", 7, 10, 7],
      ["FURY ELITE", 8, 4, 5],
      ["UGD LIGHT", 9, 8, 2],
      ["K4F", 10, 9, 8],
      ["♱VØID×STRIKE♱", 11, 11, 10],
    ],
    jogadores: [
      ["FURY ROYAL", "VN", 5, 11, 9],
      ["FURY ROYAL", "Egoist", 8, 5, 7],
      ["FURY ROYAL", "NG", 12, 6, 13],
      ["FURY ROYAL", "MARTNA", 11, 15, 8],
      ["FURY ROYAL", "Noki", 0, 0, 0],
      ["FURY ROYAL", "OFF", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.D_R", 1, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱+gute", 0, 0, 0],
      ["♱VØID×STRIKE♱", "♱Vøid♱.nino", 1, 0, 0],
      ["♱VØID×STRIKE♱", "™VØID°⁷⁷⁷", 1, 0, 0],
      ["♱VØID×STRIKE♱", "√Vøid√T9", 0, 0, 0],
      ["FURY ELITE", "DIANA", 1, 1, 7],
      ["FURY ELITE", "DEX", 3, 2, 1],
      ["FURY ELITE", "SUN", 6, 9, 3],
      ["FURY ELITE", "TRY", 0, 5, 5],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["K4F", "K4F  Éourso", 1, 1, 0],
      ["K4F", "aleke", 0, 0, 0],
      ["K4F", "K4F  Zaza", 0, 1, 1],
      ["K4F", "K4F  Nine", 0, 0, 0],
      ["K4F", "wend", 2, 2, 2],
      ["UGD Threat + Olympique", "Treon", 0, 0, 0],
      ["UGD Threat + Olympique", "Kaze", 0, 0, 0],
      ["UGD Threat + Olympique", "Arise", 0, 0, 0],
      ["UGD Threat + Olympique", "LMF_BOSS", 0, 0, 0],
      ["UGD Legends", "Buzeira", 3, 2, 1],
      ["UGD Threat + Olympique", "Sant", 0, 0, 0],
      ["UGD Legends", "Hell", 3, 8, 4],
      ["UGD Legends", "Xoxoto", 14, 13, 4],
      ["UGD Threat + Olympique", "Waze", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 2, 1, 4],
      ["UGD LIGHT", "Zann", 1, 0, 0],
      ["UGD LIGHT", "Psycho", 3, 1, 1],
      ["UGD LIGHT", "Chino", 0, 0, 0],
      ["UGD LIGHT", "Sant", 0, 0, 0],
      ["UGD LIGHT", "Cool", 0, 0, 6],
      ["CMF ATLANTIC", "CMF Léo", 14, 4, 7],
      ["CMF ATLANTIC", "CMF Syx", 14, 7, 3],
      ["CMF ATLANTIC", "CMF Kira", 13, 2, 4],
      ["CMF ATLANTIC", "CMF Moizo", 9, 4, 4],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 1, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["UGD Threat + Olympique", "Weenot", 3, 9, 3],
      ["UGD Legends", "Duardin", 0, 0, 0],
      ["UGD Legends", "Lorex", 0, 0, 0],
      ["UGD Legends", "Cants", 0, 0, 0],
      ["UGD Legends", "Santz", 10, 7, 5],
      ["UGD Threat + Olympique", "Waze", 2, 7, 3],
      ["UGD Threat + Olympique", "Kaze", 5, 4, 1],
      ["UGD Threat + Olympique", "Treon", 7, 6, 11],
      ["EmE", "Nofear", 4, 6, 0],
      ["EmE", "geldeysito", 0, 0, 0],
      ["EmE", "EME々Akaza", 4, 14, 0],
      ["EmE", "MK4", 0, 0, 0],
    ],
  },

  // ========================================
  // NOVO XTREINO? Cole um bloco novo aqui embaixo!
  // ========================================
];