// db/seed/xtreinos-dados-novo.ts
// 🆕 XTreino 9 — 2026-06-15

import type { XtreinoRaw } from "./xtreinos-dados.js";

export const xtreinosRawNovo: XtreinoRaw[] = [
  // ========================================
  // XTreino 9 — 2026-06-15
  // ========================================
  {
    id: 9,
    date: "2026-06-15",
    colocacoes: [
      ["CMF ATLANTIC", 1, 1, 3],
      ["FURY MIX (ELITE / ROYAL)", 2, 4, 5],
      ["K4F", 3, 8, 4],
      ["RED INSS", 4, 3, 1],
      ["UGD Threat", 5, 5, 2],
      ["vengeance", 6, 9, 7],
      ["CMF ASSALT", 7, 6, 9],
      ["UGD LEGENDS", 8, 2, 6],
      ["FURY CASUAL", 9, 7, 8],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD LIGHT", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["CMF ATLANTIC", "CMF Fallet", 17, 15, 14],
      ["CMF ATLANTIC", "CMF SANT", 7, 13, 4],
      ["CMF ATLANTIC", "CMF Syx⁷", 12, 14, 15],
      ["CMF ATLANTIC", "CMF M0IZO", 7, 4, 6],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["FURY MIX (ELITE / ROYAL)", "Dexz⁷ᴿʸᴸ", 5, 0, 4],
      ["FURY MIX (ELITE / ROYAL)", "B4RBOSA⁷", 10, 2, 1],
      ["FURY MIX (ELITE / ROYAL)", "NOKI FURY", 8, 4, 4],
      ["FURY MIX (ELITE / ROYAL)", "Diana FURY", 3, 3, 1],
      ["K4F", "Alek", 4, 3, 1],
      ["K4F", "K4F DUDU", 7, 1, 0],
      ["K4F", "K4F ÉoUrso", 2, 2, 1],
      ["K4F", "K4F ExuKramo", 2, 2, 1],
      ["K4F", "K4F Nine", 0, 0, 0],
      ["K4F", "Wend", 0, 0, 0],
      ["RED INSS", "RED snow777", 2, 5, 9],
      ["RED INSS", "RED APENAS", 5, 6, 4],
      ["RED INSS", "RED Thaedus⁷", 9, 5, 6],
      ["RED INSS", "RED LORD", 10, 11, 13],
      ["RED INSS", "VERON", 0, 0, 0],
      ["RED INSS", "ATREUS", 0, 0, 0],
      ["UGD Threat", "UGD cool⁷", 3, 10, 11],
      ["UGD Threat", "UGD Kaze", 1, 6, 3],
      ["UGD Threat", "UGD Treon", 12, 10, 3],
      ["UGD Threat", "UGD ARISE", 4, 6, 5],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["vengeance", "VNG NEAR★", 0, 3, 0],
      ["vengeance", "RED moraesbc", 5, 0, 0],
      ["vengeance", "Ti Pela", 1, 0, 0],
      ["vengeance", "TTKKAIKE", 3, 0, 0],
      ["vengeance", "Caveira", 0, 0, 0],
      ["vengeance", "ackerman", 0, 2, 2],
      ["vengeance", "VNG ¿¿¿", 0, 0, 2],
      ["vengeance", "VNG SCAVEIRA", 0, 1, 0],
      ["CMF ASSALT", "CMF xeW", 2, 3, 3],
      ["CMF ASSALT", "CMF Lyx7", 2, 4, 2],
      ["CMF ASSALT", "CMF Txxz¹", 1, 0, 2],
      ["CMF ASSALT", "CMF BAELTTK", 0, 3, 0],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["UGD LEGENDS", "UGD Buzeira", 0, 2, 1],
      ["UGD LEGENDS", "qgc.", 0, 2, 0],
      ["UGD LEGENDS", "CF BLAZE", 1, 3, 3],
      ["UGD LEGENDS", "UGD Santz⁷", 2, 7, 9],
      ["UGD LEGENDS", "UGD Weenot", 0, 0, 4],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 0, 0, 0],
      ["FURY CASUAL", "AM Akyra🥷", 0, 0, 0],
      ["FURY CASUAL", "FURY zLAZY⁰¹", 2, 1, 0],
      ["FURY CASUAL", "LK NPC", 0, 0, 1],
      ["FURY CASUAL", "FURY zLORHAN", 2, 2, 0],
      ["FURY CASUAL", "KILLUA", 0, 0, 0],
      ["FURY CASUAL", "VELOZZO", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
    ],
  },
  // ========================================
    // XTreino 10 — 2026-06-16
      // ========================================
        {
            id: 10,
                date: "2026-06-16",
                    colocacoes: [
                          ["CMF ATLANTIC", 1, 4, 1],
                                ["RED INSS", 2, 6, 6],
                                      ["FURY ROYAL / MIX (Line I)", 3, 1, 4],
                                            ["UGD LEGENDS", 4, 2, 3],
                                                  ["FURY ELITE / MIX (Line H)", 5, 3, 2],
                                                        ["UGD Threat", 6, 5, 5],
                                                              ["CMF ASSALT", 7, 7, 7],
                                                                    ["TROPA DO XXX", 0, 0, 0],
                                                                          ["UGD LIGHT", 0, 0, 0],
                                                                                ["UGD OLYMPIQUE", 0, 0, 0],
                                                                                    ],
                                                                                        jogadores: [
                                                                                              ["CMF ATLANTIC", "CMF Teo", 9, 8, 15],
                                                                                                    ["CMF ATLANTIC", "CMF Syx⁷", 13, 7, 14],
                                                                                                          ["CMF ATLANTIC", "CMF SANT", 7, 0, 9],
                                                                                                                ["CMF ATLANTIC", "CMF M0IZO", 9, 8, 8],
                                                                                                                      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
                                                                                                                            ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
                                                                                                                                  ["RED INSS", "RED APENAS", 2, 0, 2],
                                                                                                                                        ["RED INSS", "RED moraesbc", 1, 2, 1],
                                                                                                                                              ["RED INSS", "RED FELPZ", 0, 3, 0],
                                                                                                                                                    ["RED INSS", "RED snow777", 0, 1, 1],
                                                                                                                                                          ["FURY ROYAL / MIX (Line I)", "M4RTNA FURY", 5, 7, 8],
                                                                                                                                                                ["FURY ROYAL / MIX (Line I)", "VN' FURY", 8, 7, 6],
                                                                                                                                                                      ["FURY ROYAL / MIX (Line I)", "Sun FURY", 5, 2, 3],
                                                                                                                                                                            ["FURY ROYAL / MIX (Line I)", "NOKI FURY", 7, 4, 7],
                                                                                                                                                                                  ["UGD LEGENDS", "UGD Buzeira", 5, 1, 1],
                                                                                                                                                                                        ["UGD LEGENDS", "qgc.", 1, 3, 3],
                                                                                                                                                                                              ["UGD LEGENDS", "CF BLAZE", 7, 5, 5],
                                                                                                                                                                                                    ["UGD LEGENDS", "UGD XOXOTO", 6, 12, 0],
                                                                                                                                                                                                          ["UGD LEGENDS", "Sant", 0, 0, 0],
                                                                                                                                                                                                                ["UGD LEGENDS", "Hell", 0, 0, 0],
                                                                                                                                                                                                                      ["FURY ELITE / MIX (Line H)", "Rauan FURY", 1, 2, 2],
                                                                                                                                                                                                                            ["FURY ELITE / MIX (Line H)", "Dexz⁷ᴿʸᴸ", 2, 2, 1],
                                                                                                                                                                                                                                  ["FURY ELITE / MIX (Line H)", "B4RBOSA⁷", 6, 2, 2],
                                                                                                                                                                                                                                        ["FURY ELITE / MIX (Line H)", "Diana FURY", 2, 1, 1],
                                                                                                                                                                                                                                              ["FURY ELITE / MIX (Line H)", "TRY", 0, 0, 0],
                                                                                                                                                                                                                                                    ["FURY ELITE / MIX (Line H)", "SLUUG", 0, 0, 0],
                                                                                                                                                                                                                                                          ["UGD Threat", "UGD cool⁷", 4, 4, 3],
                                                                                                                                                                                                                                                                ["UGD Threat", "UGD Treon", 7, 8, 0],
                                                                                                                                                                                                                                                                      ["UGD Threat", "UGD ARISE", 3, 3, 0],
                                                                                                                                                                                                                                                                            ["UGD Threat", "UGD Kaze", 5, 4, 4],
                                                                                                                                                                                                                                                                                  ["UGD Threat", "LMF_BOSS", 0, 0, 0],
                                                                                                                                                                                                                                                                                        ["CMF ASSALT", "CMF xeW", 8, 1, 1],
                                                                                                                                                                                                                                                                                              ["CMF ASSALT", "CMF Lyx7", 5, 1, 1],
                                                                                                                                                                                                                                                                                                    ["CMF ASSALT", "CMF Txxz¹", 2, 0, 1],
                                                                                                                                                                                                                                                                                                          ["CMF ASSALT", "MacroSync", 0, 2, 0],
                                                                                                                                                                                                                                                                                                                ["CMF ASSALT", "CMF Max", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                            ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                  ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                        ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                              ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                    ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                          ["UGD LIGHT", "Psycho", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                ["UGD LIGHT", "Zann", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                      ["UGD LIGHT", "Kyz", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                            ["UGD LIGHT", "Chrisxz", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                                  ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                                        ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                                              ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                                                    ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
                                                                                                                                                                                                                                                                                                                                                                                                        ],
                                                                                                                                                                                                                                                                                                                                                                                                          },

];