// db/seed/xtreinos-dados-novo.ts
// 🆕 XTreino 13 — 2026-06-19

import type { XtreinoRaw } from "./xtreinos-dados.js";

export const xtreinosRawNovo: XtreinoRaw[] = [
  // ========================================
  // XTreino 13 — 2026-06-19
  // ========================================
  {
    id: 13,
    date: "2026-06-19",
    colocacoes: [
      ["CMF ATLANTIC", 1, 5, 1],
      ["FURY ELITE", 2, 2, 4],
      ["FURY ROYAL", 3, 6, 8],
      ["UGD Threat", 4, 1, 3],
      ["UGD LEGENDS", 5, 3, 6],
      ["K4F", 6, 4, 2],
      ["UGD LIGHT", 7, 7, 7],
      ["CMF ASSALT", 8, 8, 5],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
      ["CPF VILTRUMITE", 0, 0, 0],
    ],
    jogadores: [
      ["CMF ATLANTIC", "CMF Syx", 10, 14, 20],
      ["CMF ATLANTIC", "CMF KIRA", 9, 6, 12],
      ["CMF ATLANTIC", "CMF Leo", 18, 12, 8],
      ["CMF ATLANTIC", "CMF MOIZO", 4, 5, 9],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["FURY ELITE", "NOKI FURY", 11, 9, 1],
      ["FURY ELITE", "Rauan FURY", 1, 6, 4],
      ["FURY ELITE", "Dexz⁷RYL", 7, 0, 0],
      ["FURY ELITE", "DIANA FURY", 3, 2, 2],
      ["FURY ELITE", "V0XEN!", 0, 0, 1],
      ["FURY ELITE", "DEX", 0, 0, 0],
      ["FURY ELITE", "SUN", 0, 0, 0],
      ["FURY ELITE", "TRY", 0, 0, 0],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["FURY ROYAL", "M4RTNA FURY", 5, 7, 3],
      ["FURY ROYAL", "Sun FURY", 3, 2, 0],
      ["FURY ROYAL", "Asmota", 4, 2, 0],
      ["FURY ROYAL", "Egoist FURY", 3, 2, 0],
      ["UGD Threat", "Cool", 0, 0, 0],
      ["UGD Threat", "Treon", 5, 20, 12],
      ["UGD Threat", "Kaze", 3, 11, 13],
      ["UGD Threat", "Arise", 9, 4, 4],
      ["UGD Threat", "LOREX", 5, 15, 10],
      ["UGD Threat", "Santz", 0, 0, 0],
      ["UGD LEGENDS", "Buzeira", 1, 3, 3],
      ["UGD LEGENDS", "Duardin", 4, 5, 7],
      ["UGD LEGENDS", "Ohara", 3, 3, 7],
      ["UGD LEGENDS", "Hyuga⁷", 5, 4, 2],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Xoxoto", 0, 0, 0],
      ["UGD LEGENDS", "Blaze", 0, 0, 0],
      ["UGD LEGENDS", "Gabriel qgc", 0, 0, 0],
      ["K4F", "K4F Nine", 0, 0, 2],
      ["K4F", "K4F zaza", 0, 0, 3],
      ["K4F", "Guilok07", 1, 2, 0],
      ["K4F", "K4F Éourso", 1, 1, 0],
      ["K4F", "NyE Wendxz", 0, 3, 10],
      ["K4F", "KISE", 0, 0, 3],
      ["K4F", "K4F GUI", 0, 0, 0],
      ["K4F", "K4F Aleke", 0, 0, 0],
      ["K4F", "K4F Dudu", 0, 0, 0],
      ["K4F", "wend", 0, 0, 0],
      ["UGD LIGHT", "Psycho", 2, 0, 2],
      ["UGD LIGHT", "Santz⁷", 4, 0, 0],
      ["UGD LIGHT", "V0XEN!", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Xezn⁷", 0, 0, 4],
      ["UGD LIGHT", "Dexz⁷RYL", 0, 0, 1],
      ["CMF ASSALT", "CMF Txxz¹", 3, 1, 4],
      ["CMF ASSALT", "CMF BAELTTK", 1, 2, 1],
      ["CMF ASSALT", "CMF xeW", 0, 2, 0],
      ["CMF ASSALT", "CMF Lyx7", 2, 2, 7],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
      ["UGD OLYMPIQUE", "Sant", 0, 0, 0],
      ["CPF VILTRUMITE", "Ice", 0, 0, 0],
      ["CPF VILTRUMITE", "Biscoito", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF gbzin", 0, 0, 0],
      ["CPF VILTRUMITE", "[CPF]xitado", 0, 0, 0],
    ],
  },
];