// db/seed/xtreinos-dados-novo.ts
// 🆕 XTreino 10 — 2026-06-16

import type { XtreinoRaw } from "./xtreinos-dados.js";

export const xtreinosRawNovo: XtreinoRaw[] = [
  // ========================================
  // XTreino 10 — 2026-06-16
  // ========================================
  {
    id: 10,
    date: "2026-06-16",
    colocacoes: [
      ["CMF ATLANTIC", 1, 4, 1],
      ["RED INSS", 2, 6, 6],
      ["FURY ROYAL / MIX (Line I)", 3, 1, 4],
      ["UGD LEGENDS", 4, 2, 3],
      ["FURY ELITE / MIX (Line H)", 5, 3, 2],
      ["UGD Threat", 6, 5, 5],
      ["CMF ASSALT", 7, 7, 7],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD LIGHT", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["CMF ATLANTIC", "CMF Teo", 9, 8, 15],
      ["CMF ATLANTIC", "CMF Syx⁷", 13, 7, 14],
      ["CMF ATLANTIC", "CMF SANT", 7, 0, 9],
      ["CMF ATLANTIC", "CMF M0IZO", 9, 8, 8],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["RED INSS", "RED APENAS", 2, 0, 2],
      ["RED INSS", "RED moraesbc", 1, 2, 1],
      ["RED INSS", "RED FELPZ", 0, 3, 0],
      ["RED INSS", "RED snow777", 0, 1, 1],
      ["FURY ROYAL / MIX (Line I)", "M4RTNA FURY", 5, 7, 8],
      ["FURY ROYAL / MIX (Line I)", "VN' FURY", 8, 7, 6],
      ["FURY ROYAL / MIX (Line I)", "Sun FURY", 5, 2, 3],
      ["FURY ROYAL / MIX (Line I)", "NOKI FURY", 7, 4, 7],
      ["UGD LEGENDS", "UGD Buzeira", 5, 1, 1],
      ["UGD LEGENDS", "qgc.", 1, 3, 3],
      ["UGD LEGENDS", "CF BLAZE", 7, 5, 5],
      ["UGD LEGENDS", "UGD XOXOTO", 6, 12, 0],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["FURY ELITE / MIX (Line H)", "Rauan FURY", 1, 2, 2],
      ["FURY ELITE / MIX (Line H)", "Dexz⁷ᴿʸᴸ", 2, 2, 1],
      ["FURY ELITE / MIX (Line H)", "B4RBOSA⁷", 6, 2, 2],
      ["FURY ELITE / MIX (Line H)", "Diana FURY", 2, 1, 1],
      ["FURY ELITE / MIX (Line H)", "TRY", 0, 0, 0],
      ["FURY ELITE / MIX (Line H)", "SLUUG", 0, 0, 0],
      ["UGD Threat", "UGD cool⁷", 4, 4, 3],
      ["UGD Threat", "UGD Treon", 7, 8, 0],
      ["UGD Threat", "UGD ARISE", 3, 3, 0],
      ["UGD Threat", "UGD Kaze", 5, 4, 4],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["CMF ASSALT", "CMF xeW", 8, 1, 1],
      ["CMF ASSALT", "CMF Lyx7", 5, 1, 1],
      ["CMF ASSALT", "CMF Txxz¹", 2, 0, 1],
      ["CMF ASSALT", "MacroSync", 0, 2, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Kyz", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
    ],
  },
];