// db/seed/xtreinos-dados-novo.ts
// 🆕 XTreino 11 — 2026-06-17

import type { XtreinoRaw } from "./xtreinos-dados.js";

export const xtreinosRawNovo: XtreinoRaw[] = [
  // ========================================
  // XTreino 11 — 2026-06-17
  // ========================================
  {
    id: 11,
    date: "2026-06-17",
    colocacoes: [
      ["UGD Threat", 1, 4, 2],
      ["UGD LIGHT", 2, 9, 0],
      ["K4F", 3, 6, 8],
      ["CMF ATLANTIC", 4, 3, 4],
      ["UGD LEGENDS", 5, 8, 5],
      ["CPF VILTRUMITE", 6, 5, 6],
      ["FURY ROYAL", 7, 1, 1],
      ["CMF ASSALT", 8, 7, 3],
      ["FURY ELITE", 9, 2, 7],
      ["TROPA DO XXX", 0, 0, 0],
      ["UGD OLYMPIQUE", 0, 0, 0],
    ],
    jogadores: [
      ["UGD Threat", "Kaze", 8, 2, 5],
      ["UGD Threat", "Arise", 11, 4, 5],
      ["UGD Threat", "Santz", 14, 3, 10],
      ["UGD Threat", "Treon", 9, 5, 9],
      ["UGD Threat", "Cool", 0, 0, 0],
      ["UGD LIGHT", "Nofear'", 2, 0, 0],
      ["UGD LIGHT", "Xezn'", 1, 0, 0],
      ["UGD LIGHT", "UGD JEM", 3, 0, 0],
      ["UGD LIGHT", "UGD Kyz`", 1, 0, 0],
      ["UGD LIGHT", "Psycho", 0, 0, 0],
      ["UGD LIGHT", "Zann", 0, 0, 0],
      ["UGD LIGHT", "Chrisxz", 0, 0, 0],
      ["K4F", "Alek", 2, 0, 0],
      ["K4F", "K4F NINE", 4, 0, 2],
      ["K4F", "K4F Zaza", 2, 0, 0],
      ["K4F", "Guilok07", 3, 1, 0],
      ["K4F", "NyE Wendxz", 0, 1, 0],
      ["K4F", "K4F ÉOurso", 0, 0, 0],
      ["K4F", "K4F GUI", 0, 0, 0],
      ["K4F", "K4F Aleke", 0, 0, 0],
      ["K4F", "K4F Dudu", 0, 0, 0],
      ["K4F", "wend", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Syx7", 12, 14, 10],
      ["CMF ATLANTIC", "CMF Teo", 5, 6, 0],
      ["CMF ATLANTIC", "CMF KIRA", 8, 5, 2],
      ["CMF ATLANTIC", "CMF M0IZO", 6, 3, 4],
      ["CMF ATLANTIC", "CMF MOZKA", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Smoke", 0, 0, 0],
      ["CMF ATLANTIC", "CMF Sant", 0, 0, 0],
      ["UGD LEGENDS", "Buzeira", 1, 0, 2],
      ["UGD LEGENDS", "Gabriel qgc", 5, 0, 1],
      ["UGD LEGENDS", "Blaze", 1, 0, 2],
      ["UGD LEGENDS", "Xoxoto", 6, 2, 4],
      ["UGD LEGENDS", "Hell", 0, 0, 0],
      ["UGD LEGENDS", "Sant", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF gbzin", 0, 1, 0],
      ["CPF VILTRUMITE", "CPF zkrw", 0, 0, 0],
      ["CPF VILTRUMITE", "Ice", 1, 0, 0],
      ["CPF VILTRUMITE", "Biscoito", 5, 0, 0],
      ["CPF VILTRUMITE", "[CPF]xitado", 0, 1, 0],
      ["CPF VILTRUMITE", "CPF GBZIN", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF BISCOITO", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF KROM", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF ICE KILER", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF XITADO", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF LUIZ", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF PICASSO", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF SHOTTZZ", 0, 0, 0],
      ["CPF VILTRUMITE", "CPF FLAX", 0, 0, 0],
      ["FURY ROYAL", "M4RTNA FURY", 6, 11, 12],
      ["FURY ROYAL", "NGLIFE FURY", 4, 12, 14],
      ["FURY ROYAL", "VN' FURY", 7, 5, 13],
      ["FURY ROYAL", "Egoist FURY", 5, 12, 4],
      ["CMF ASSALT", "CMF Txxz¹", 3, 0, 4],
      ["CMF ASSALT", "CMF Lyx7", 1, 0, 4],
      ["CMF ASSALT", "CMF BAELTTK", 1, 2, 3],
      ["CMF ASSALT", "CMF xeW", 1, 1, 1],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["CMF ASSALT", "CMF Thxxxz", 0, 0, 0],
      ["FURY ELITE", "Diana FURY", 1, 0, 2],
      ["FURY ELITE", "Rauan FURY", 3, 2, 2],
      ["FURY ELITE", "Dexz7RYL", 0, 1, 0],
      ["FURY ELITE", "try FURY", 1, 1, 0],
      ["FURY ELITE", "DIANA", 0, 0, 0],
      ["FURY ELITE", "DEX", 0, 0, 0],
      ["FURY ELITE", "SUN", 0, 0, 0],
      ["FURY ELITE", "TRY", 0, 0, 0],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 0, 0, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 0, 0, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 0, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD OLYMPIQUE", "Weenot", 0, 0, 0],
      ["UGD OLYMPIQUE", "Duardin", 0, 0, 0],
      ["UGD OLYMPIQUE", "Lorex", 0, 0, 0],
      ["UGD OLYMPIQUE", "Cants", 0, 0, 0],
    ],
  },
];