// db/seed/xtreinos-dados-novo.ts
// 🆕 XTreino 8 — 2026-06-11 (editado no celular)

import type { XtreinoRaw } from "./xtreinos-dados.js";

export const xtreinosRawNovo: XtreinoRaw[] = [
  // ========================================
  // XTreino 8 — 2026-06-11
  // ========================================
  {
    id: 8,
    date: "2026-06-11",
    colocacoes: [
      ["FURY ROYAL", 1, 4, 1],
      ["UGD OLYMPIQUE / LEGENDS", 2, 2, 2],
      ["Randolinhas", 3, 1, 0],
      ["UGD LIGHT", 4, 5, 5],
      ["FURY ELITE", 5, 8, 7],
      ["TROPA DO XXX", 6, 9, 9],
      ["UGD Threat", 7, 3, 4],
      ["CMF ATLANTIC", 8, 10, 6],
      ["CMF ASSALT", 9, 7, 3],
      ["K4F", 10, 6, 8],
    ],
    jogadores: [
      ["FURY ROYAL", "MARTNA", 8, 5, 16],
      ["FURY ROYAL", "NG", 7, 6, 8],
      ["FURY ROYAL", "Egoist", 14, 9, 10],
      ["FURY ROYAL", "Noki", 7, 6, 10],
      ["FURY ROYAL", "VN", 0, 0, 0],
      ["FURY ROYAL", "OFF", 0, 0, 0],
      ["UGD OLYMPIQUE / LEGENDS", "Cants", 12, 4, 7],
      ["UGD OLYMPIQUE / LEGENDS", "Weenot", 7, 5, 9],
      ["UGD OLYMPIQUE / LEGENDS", "Xoxoto", 10, 5, 0],
      ["UGD OLYMPIQUE / LEGENDS", "Buzeira", 3, 4, 6],
      ["Randolinhas", "sinner boy", 13, 16, 0],
      ["Randolinhas", "Miag", 10, 14, 0],
      ["Randolinhas", "VAL Yzzi⁷", 18, 13, 0],
      ["Randolinhas", "7xis ╲ Tilapia", 8, 14, 0],
      ["UGD LIGHT", "Xezn⁷", 0, 0, 1],
      ["UGD LIGHT", "Psycho", 2, 3, 5],
      ["UGD LIGHT", "Chrisxz", 1, 2, 0],
      ["UGD LIGHT", "Kyz", 1, 6, 3],
      ["FURY ELITE", "TRY", 2, 3, 0],
      ["FURY ELITE", "SUN", 6, 3, 1],
      ["FURY ELITE", "DIANA", 2, 2, 1],
      ["FURY ELITE", "DEX", 1, 2, 1],
      ["FURY ELITE", "SLUUG", 0, 0, 0],
      ["FURY ELITE", "RAUAN", 0, 0, 0],
      ["TROPA DO XXX", "AMN Y2K", 2, 0, 0],
      ["TROPA DO XXX", "XXX Pedrozin", 1, 2, 0],
      ["TROPA DO XXX", "!Iagoperesㅤ🃏", 3, 3, 0],
      ["TROPA DO XXX", "XXX Rip_sw🤫", 4, 3, 0],
      ["TROPA DO XXX", "XXX †Crinsom", 0, 0, 0],
      ["TROPA DO XXX", "XXX China🇨🇳", 0, 0, 0],
      ["UGD Threat", "Cool", 3, 6, 0],
      ["UGD Threat", "Kaze", 1, 4, 5],
      ["UGD Threat", "Treon", 4, 10, 6],
      ["UGD Threat", "Arise", 2, 1, 4],
      ["UGD Threat", "LMF_BOSS", 0, 0, 0],
      ["CMF ATLANTIC", "CMF MOZKAXR", 4, 1, 3],
      ["CMF ATLANTIC", "CMF Smoke", 2, 0, 5],
      ["CMF ATLANTIC", "CMF SANT", 2, 4, 5],
      ["CMF ATLANTIC", "CMF Moizo", 3, 2, 3],
      ["CMF ATLANTIC", "CMF Syx", 0, 0, 0],
      ["CMF ASSALT", "CMF Lynx7", 4, 1, 7],
      ["CMF ASSALT", "Artur", 6, 0, 5],
      ["CMF ASSALT", "CMF Txxz¹", 4, 1, 5],
      ["CMF ASSALT", "CMF xeW", 0, 1, 5],
      ["CMF ASSALT", "CMF Dnvy", 0, 0, 0],
      ["CMF ASSALT", "CMF Max", 0, 0, 0],
      ["K4F", "K4F  Éourso", 0, 1, 1],
      ["K4F", "aleke", 0, 2, 2],
      ["K4F", "wend", 2, 4, 1],
      ["K4F", "K4F  Nine", 2, 1, 4],
      ["K4F", "K4F  Zaza", 0, 0, 0],
    ],
  },
];